version: '3.8'
services:
  nginx:
    image: nginx:1.20.1-alpine
    ports:
      - '8100:80' #test feature
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/app/www
    links:
      - php-fpm
  php-fpm:
    container_name: php-fpm-fpm
    image: php:7.4-fpm-alpine
    expose:
      - '9000'
    volumes:
      - ./php-fpm/app:/app





