version: '3.8'
services:
  nginx:
    image: nginx:1.20.1-alpine
    ports:
      - '8100:80' #test feature
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/app/www
    links:
      - php-fpm
  php-fpm:
    build:
      context: php/docker
      dockerfile: php-fpm.docker
    expose:
      - '9000'
    volumes:
      - ./php/app:/app
    links:
      - mysql
  php-cli:
    build:
      context: php/docker
      dockerfile: php-cli.docker
    volumes:
      - ./php/app:/app
    links:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    ports:
      - '127.0.0.1:33080:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

